module.exports = () => ({
  code: 0,
  msg: 'Success',
  data: {
    res_list: [
      {
        id: 47,
        group_name: '页面中创建的3',
        rule_des: '',
        run_status: '2',
        api_status: true,
        og_query: {
          relation: 'and',
          rules: [
            {
              relation: 'and',
              rules: [
                {
                  relation: 'and',
                  rules: [
                    {
                      filters: [
                        {
                          field: 'role',
                          function: '',
                          params: ['student'],
                          type: 'filter',
                          _name: '用户角色',
                        },
                      ],
                      function: '=',
                      field: 'count',
                      time_params: ['2021-03-19', '2021-03-21'],
                      params: [1],
                      evt: 'view',
                      ubt: {
                        app: ['wk'],
                        project: [],
                        scene: [],
                        page: [],
                        element: [],
                      },
                      type: 'event_rule',
                    },
                    {
                      filters: [
                        {
                          field: 'pay_count',
                          function: '',
                          params: ['1111'],
                          type: 'filter',
                          _name: '用户历史的支付次数',
                        },
                      ],
                      function: '>',
                      field: 'count',
                      time_params: ['2021-03-24', '2021-03-26'],
                      params: [2222],
                      evt: 'view',
                      ubt: {
                        app: ['wk'],
                        project: [],
                        scene: [],
                        page: [],
                        element: [],
                      },
                      type: 'event_rule',
                    },
                  ],
                  type: 'rules_relation',
                  name: 'user_action',
                },
              ],
              type: 'rules_relation',
              name: 'user_action',
            },
          ],
          type: 'rules_relation',
        },
        group_count: 0,
        refresh_time: '2021-03-24 14:09',
      },
      {
        id: 46,
        group_name: '22222',
        rule_des: '',
        run_status: '-1',
        api_status: false,
        og_query: {
          relation: 'and',
          rules: [
            {
              relation: 'and',
              rules: [
                {
                  filters: [],
                  function: '=',
                  field: 'count',
                  time_params: ['2021-3-24', '2021-3-24'],
                  params: [1],
                  evt: 'view',
                  ubt: {
                    app: ['wk'],
                    project: [],
                    scene: [],
                    page: [],
                    element: [],
                  },
                  type: 'event_rule',
                },
              ],
              type: 'rules_relation',
              name: 'user_action',
            },
          ],
          type: 'rules_relation',
        },
        group_count: 0,
        refresh_time: '',
      },
      {
        id: 45,
        group_name: '22222',
        rule_des: '',
        run_status: '0',
        api_status: false,
        og_query: {
          relation: 'and',
          rules: [
            {
              relation: 'and',
              rules: [
                {
                  filters: [],
                  function: '=',
                  field: 'count',
                  time_params: ['2021-3-24', '2021-3-24'],
                  params: [1],
                  evt: 'view',
                  ubt: {
                    app: ['wk'],
                    project: [],
                    scene: [],
                    page: [],
                    element: [],
                  },
                  type: 'event_rule',
                },
              ],
              type: 'rules_relation',
              name: 'user_action',
            },
          ],
          type: 'rules_relation',
        },
        group_count: 0,
        refresh_time: '2021-03-24 12:56',
      },
      {
        id: 44,
        group_name: '22222',
        rule_des: '',
        run_status: '1',
        api_status: false,
        og_query: {
          relation: 'and',
          rules: [
            {
              relation: 'and',
              rules: [
                {
                  field: 'country',
                  function: '=',
                  params: ['中国'],
                  type: 'user_rule',
                  _name: '用户微信的国家信息',
                  _type: 'char',
                  tag_name: 'country',
                  tag_des: '用户微信的国家信息',
                  tag_type: 'char',
                },
              ],
              type: 'rules_relation',
              name: 'user_property',
            },
            {
              relation: 'and',
              rules: [
                {
                  filters: [],
                  function: '=',
                  field: 'count',
                  time_params: ['2021-3-24', '2021-3-24'],
                  params: [1],
                  evt: 'view',
                  ubt: {
                    app: ['wk'],
                    project: [],
                    scene: [],
                    page: [],
                    element: [],
                  },
                  type: 'event_rule',
                },
              ],
              type: 'rules_relation',
              name: 'user_action',
            },
          ],
          type: 'rules_relation',
        },
        group_count: 0,
        refresh_time: '2021-06-02 11:45',
      },
      {
        id: 43,
        group_name: '测试',
        rule_des: '',
        run_status: '4',
        api_status: false,
        og_query: {
          relation: 'and',
          rules: [
            {
              relation: 'or',
              rules: [
                {
                  relation: 'and',
                  rules: [
                    {
                      field: 'role',
                      function: '=',
                      params: ['student'],
                      type: 'user_rule',
                      _name: '用户角色',
                      _type: 'char',
                      tag_name: 'role',
                      tag_des: '用户角色',
                      tag_type: 'char',
                      options: {
                        student: '学员',
                        lecturer: '讲师',
                        platformee: '平台帐号',
                      },
                    },
                    {
                      field: 'first_pay_time',
                      function: '>',
                      params: ['2020-01-01'],
                      type: 'user_rule',
                      _name: '第一次付费时间',
                      _type: 'char',
                      tag_name: 'first_pay_time',
                      tag_des: '第一次付费时间',
                      tag_type: 'char',
                    },
                    {
                      field: 'last_pay_time',
                      function: 'nd~now',
                      params: [7],
                      type: 'user_rule',
                      _name: '最后一次付费时间',
                      _type: 'char',
                      tag_name: 'last_pay_time',
                      tag_des: '最后一次付费时间',
                      tag_type: 'char',
                    },
                    {
                      field: 'sex',
                      function: '=',
                      params: ['1'],
                      type: 'user_rule',
                      _name: '用户在微信录入的性别',
                      _type: 'char',
                      tag_name: 'sex',
                      tag_des: '用户在微信录入的性别',
                      tag_type: 'char',
                      options: {
                        0: '未知',
                        1: '男',
                        2: '女',
                      },
                    },
                  ],
                  type: 'rules_relation',
                  name: 'user_property',
                },
                {
                  field: 'pay_count',
                  function: '>',
                  params: [2],
                  type: 'user_rule',
                  _name: '用户历史的支付次数',
                  _type: 'number',
                  tag_name: 'pay_count',
                  tag_des: '用户历史的支付次数',
                  tag_type: 'number',
                },
              ],
              type: 'rules_relation',
              name: 'user_property',
            },
            {
              relation: 'or',
              rules: [
                {
                  relation: 'and',
                  rules: [
                    {
                      filters: [
                        {
                          field: 'role',
                          function: '',
                          params: ['student'],
                          type: 'filter',
                          _name: '用户角色',
                        },
                      ],
                      function: '>',
                      field: 'count',
                      time_params: ['2021-03-01', '2021-03-10'],
                      params: [2],
                      evt: 'view',
                      ubt: {
                        app: ['wk'],
                        project: [],
                        scene: [],
                        page: [],
                        element: [],
                      },
                      type: 'event_rule',
                    },
                    {
                      filters: [
                        {
                          field: 'role',
                          function: '',
                          params: ['student'],
                          type: 'filter',
                          _name: '用户角色',
                        },
                      ],
                      function: '>',
                      field: 'count',
                      time_params: ['2021-03-11', '2021-03-20'],
                      params: [1],
                      evt: 'click',
                      ubt: {
                        app: ['wk'],
                        project: [],
                        scene: [],
                        page: [],
                        element: ['top_banner'],
                      },
                      type: 'event_rule',
                    },
                  ],
                  type: 'rules_relation',
                  name: 'user_action',
                },
                {
                  filters: [
                    {
                      field: 'role',
                      function: '',
                      params: ['student'],
                      type: 'filter',
                      _name: '用户角色',
                    },
                  ],
                  function: '>',
                  field: 'sum',
                  time_params: ['2021-02-20', '2021-03-22'],
                  params: [20],
                  evt: 'click',
                  ubt: {
                    app: ['wk'],
                    project: [],
                    scene: [],
                    page: [],
                    element: ['rec_list_x'],
                  },
                  type: 'event_rule',
                },
              ],
              type: 'rules_relation',
              name: 'user_action',
            },
          ],
          type: 'rules_relation',
        },
        group_count: 0,
        refresh_time: '2021-06-04 17:57',
      },
      {
        id: 42,
        group_name: '测试',
        rule_des: '',
        run_status: '3',
        api_status: false,
        og_query: {
          relation: 'and',
          rules: [
            {
              relation: 'or',
              rules: [
                {
                  relation: 'and',
                  rules: [
                    {
                      field: 'role',
                      function: '=',
                      params: ['student'],
                      type: 'user_rule',
                      _name: '用户角色',
                      _type: 'char',
                      tag_name: 'role',
                      tag_des: '用户角色',
                      tag_type: 'char',
                      options: {
                        student: '学员',
                        lecturer: '讲师',
                        platformee: '平台帐号',
                      },
                    },
                    {
                      field: 'first_pay_time',
                      function: '>',
                      params: ['2020-01-01'],
                      type: 'user_rule',
                      _name: '第一次付费时间',
                      _type: 'char',
                      tag_name: 'first_pay_time',
                      tag_des: '第一次付费时间',
                      tag_type: 'char',
                    },
                    {
                      field: 'last_pay_time',
                      function: 'nd~now',
                      params: [7],
                      type: 'user_rule',
                      _name: '最后一次付费时间',
                      _type: 'char',
                      tag_name: 'last_pay_time',
                      tag_des: '最后一次付费时间',
                      tag_type: 'char',
                    },
                    {
                      field: 'sex',
                      function: '=',
                      params: ['1'],
                      type: 'user_rule',
                      _name: '用户在微信录入的性别',
                      _type: 'char',
                      tag_name: 'sex',
                      tag_des: '用户在微信录入的性别',
                      tag_type: 'char',
                      options: {
                        0: '未知',
                        1: '男',
                        2: '女',
                      },
                    },
                  ],
                  type: 'rules_relation',
                  name: 'user_property',
                },
                {
                  field: 'pay_count',
                  function: '>',
                  params: [2],
                  type: 'user_rule',
                  _name: '用户历史的支付次数',
                  _type: 'number',
                  tag_name: 'pay_count',
                  tag_des: '用户历史的支付次数',
                  tag_type: 'number',
                },
              ],
              type: 'rules_relation',
              name: 'user_property',
            },
            {
              relation: 'or',
              rules: [
                {
                  relation: 'and',
                  rules: [
                    {
                      filters: [
                        {
                          field: 'role',
                          function: '',
                          params: ['student'],
                          type: 'filter',
                          _name: '用户角色',
                        },
                      ],
                      function: '>',
                      field: 'count',
                      time_params: ['2021-03-01', '2021-03-10'],
                      params: [2],
                      evt: 'view',
                      ubt: {
                        app: ['wk'],
                        project: [],
                        scene: [],
                        page: [],
                        element: [],
                      },
                      type: 'event_rule',
                    },
                    {
                      filters: [
                        {
                          field: 'role',
                          function: '',
                          params: ['student'],
                          type: 'filter',
                          _name: '用户角色',
                        },
                      ],
                      function: '>',
                      field: 'count',
                      time_params: ['2021-03-11', '2021-03-20'],
                      params: [1],
                      evt: 'click',
                      ubt: {
                        app: ['wk'],
                        project: [],
                        scene: [],
                        page: [],
                        element: ['top_banner'],
                      },
                      type: 'event_rule',
                    },
                  ],
                  type: 'rules_relation',
                  name: 'user_action',
                },
                {
                  filters: [
                    {
                      field: 'role',
                      function: '',
                      params: ['student'],
                      type: 'filter',
                      _name: '用户角色',
                    },
                  ],
                  function: '>',
                  field: 'sum',
                  time_params: ['2021-02-20', '2021-03-22'],
                  params: [20],
                  evt: 'click',
                  ubt: {
                    app: ['wk'],
                    project: [],
                    scene: [],
                    page: [],
                    element: ['rec_list_x'],
                  },
                  type: 'event_rule',
                },
              ],
              type: 'rules_relation',
              name: 'user_action',
            },
          ],
          type: 'rules_relation',
        },
        group_count: 119056,
        refresh_time: '2021-04-07 23:57',
      },
    ],
    count: 6,
  },
});
